"""
Blocker Alignment Analysis - Before/After Unit Alignment

This module aligns units across before/after recording pairs based on:
- Coordinate proximity (row, col)
- Response signature similarity
- Waveform signature similarity

Pairing logic:
- Uses pair_id from the CSV file index (generated by discover_files.py)
- "Before" file: Condition contains play_optimization_set6_a_ipRGC_without_step()
- "After" file: Condition contains play_optimization_set6_a_ipRGC_manual()
  AND immediately follows the before file (by timestamp) AND same Chip

Cell type classification:
- ON: Increased firing 1-3s after light ON
- OFF: Increased firing 6-8s (1-3s after light OFF)
- ON_OFF: Both ON and OFF responses
- unknown: Does not meet classification thresholds
"""

import logging
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any, Union
from dataclasses import dataclass

import numpy as np
import pandas as pd
import h5py

# Import config
try:
    from .specific_config import (
        ACTIVE_EXPERIMENT,
        OUTPUT_DIR,
        GSHEET_CSV_PATH,
        FILE_INDEX_CSV,
        ALIGNED_OUTPUT_DIR,
        PROJECT_ROOT,
        BEFORE_CONDITION,
        AFTER_CONDITION,
        gsheet_filename_to_disk,
    )
except ImportError:
    from specific_config import (
        ACTIVE_EXPERIMENT,
        OUTPUT_DIR,
        GSHEET_CSV_PATH,
        FILE_INDEX_CSV,
        ALIGNED_OUTPUT_DIR,
        PROJECT_ROOT,
        BEFORE_CONDITION,
        AFTER_CONDITION,
        gsheet_filename_to_disk,
    )

# =============================================================================
# Constants
# =============================================================================

# Alignment parameters
DEFAULT_QUALITY_THRESHOLD = 0.05
DEFAULT_WAVEFORM_WEIGHT = 10.0
DEFAULT_ITERATION_DISTANCES = [0, 1, 2]

# Step light response parameters
STEP_SECTION_NAME = "step_up_5s_5i_b0_3x"  # Section name for step light
STEP_BIN_SIZE_MS = 50  # Bin size for PSTH in milliseconds
STEP_SAMPLE_RATE = 20000  # Sample rate in Hz

# Cell type labeling parameters (based on step response)
ON_CELL_PARAMS = {
    "quality_threshold": 0.1,
    "response_range": [20, 60],     # 1000-3000ms (1-3s sustained ON response)
    "baseline_range": [0, 10],      # 0-500ms (early response as baseline)
    "response_std_threshold": 0.1,
}

OFF_CELL_PARAMS = {
    "quality_threshold": 0.1,
    "response_range": [120, 160],   # 6000-8000ms (1-3s after step OFF at 5s)
    "baseline_range": [100, 110],   # 5000-5500ms (early OFF response as baseline)
    "response_std_threshold": 0.1,
}


# =============================================================================
# Data Classes
# =============================================================================

@dataclass
class FilePair:
    """Represents a before/after file pair for alignment."""
    before_file: str  # gsheet filename format (dots)
    after_file: str   # gsheet filename format (dots)
    before_h5: Path   # H5 file path
    after_h5: Path    # H5 file path
    chip: str         # Chip number
    genotype: str     # Genotype
    pair_id: str      # Pair ID from CSV index
    before_time: datetime
    after_time: datetime


@dataclass
class UnitData:
    """Data for a single unit."""
    unit_id: str
    row: int
    col: int
    waveform: np.ndarray
    response_signature: np.ndarray
    quality_index: float
    spike_times: Optional[np.ndarray] = None
    cell_type: str = "unknown"  # ON, OFF, ON_OFF, or unknown
    step_response_trials: Optional[np.ndarray] = None


# =============================================================================
# Logging Setup
# =============================================================================

def setup_logging(level: int = logging.INFO):
    """Configure logging."""
    logging.basicConfig(
        level=level,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


# =============================================================================
# Filename Utilities
# =============================================================================

def gsheet_to_h5_filename(gsheet_filename: str) -> str:
    """
    Convert gsheet filename format to H5 filename format.

    Example: "2025.09.04.10.11.09.Rec.cmcr" -> "2025.09.04-10.11.09-Rec.h5"
    """
    # First convert to disk format (hyphens)
    disk_name = gsheet_filename_to_disk(gsheet_filename)
    # Replace .cmcr with .h5
    return disk_name.replace(".cmcr", ".h5")


def extract_timestamp_from_filename(filename: str) -> Optional[datetime]:
    """
    Extract timestamp from gsheet filename.

    Example: "2025.09.04.10.11.09.Rec.cmcr" -> datetime(2025, 9, 4, 10, 11, 9)
    """
    try:
        base = filename.replace(".cmcr", "").replace(".h5", "")
        base = base.replace("-", ".")
        parts = base.split(".")

        if len(parts) >= 6:
            year = int(parts[0])
            month = int(parts[1])
            day = int(parts[2])
            hour = int(parts[3])
            minute = int(parts[4])
            second = int(parts[5])
            return datetime(year, month, day, hour, minute, second)
    except (ValueError, IndexError):
        pass
    return None


# =============================================================================
# Pair Discovery from CSV Index
# =============================================================================

def find_alignment_pairs_from_index(
    index_csv: Path = FILE_INDEX_CSV,
    h5_folder: Path = OUTPUT_DIR,
) -> List[FilePair]:
    """
    Find before/after file pairs from the CSV file index.

    Uses pair_id to link before and gaba_gly recordings that were
    validated by temporal ordering in discover_files.py.

    Args:
        index_csv: Path to file_index.csv
        h5_folder: Folder containing processed H5 files

    Returns:
        List of FilePair objects
    """
    logger = logging.getLogger(__name__)

    if not index_csv.exists():
        logger.error(f"File index not found: {index_csv}")
        return []

    df = pd.read_csv(index_csv)
    logger.info(f"Loaded file index: {len(df)} rows")

    pairs = []

    # Get unique pair_ids (excluding empty/NaN)
    pair_ids = df[df["pair_id"].notna() & (df["pair_id"] != "")]["pair_id"].unique()
    logger.info(f"Found {len(pair_ids)} unique pair IDs")

    for pair_id in sorted(pair_ids):
        pair_rows = df[df["pair_id"] == pair_id]

        before_rows = pair_rows[pair_rows["recording_type"] == "before"]
        after_rows = pair_rows[pair_rows["recording_type"] == "gaba_gly"]

        if before_rows.empty or after_rows.empty:
            logger.warning(f"Incomplete pair {pair_id}: before={len(before_rows)}, after={len(after_rows)}")
            continue

        before_row = before_rows.iloc[0]
        after_row = after_rows.iloc[0]

        # Get H5 filenames
        before_gsheet = str(before_row["gsheet_filename"])
        after_gsheet = str(after_row["gsheet_filename"])

        before_h5_name = gsheet_to_h5_filename(before_gsheet)
        after_h5_name = gsheet_to_h5_filename(after_gsheet)

        before_h5_path = h5_folder / before_h5_name
        after_h5_path = h5_folder / after_h5_name

        if not before_h5_path.exists():
            logger.warning(f"Before H5 not found: {before_h5_path}")
            continue

        if not after_h5_path.exists():
            logger.warning(f"After H5 not found: {after_h5_path}")
            continue

        before_time = extract_timestamp_from_filename(before_gsheet)
        after_time = extract_timestamp_from_filename(after_gsheet)

        if before_time is None or after_time is None:
            logger.warning(f"Could not parse timestamps for pair {pair_id}")
            continue

        chip = str(before_row.get("chip", ""))
        genotype = str(before_row.get("genotype", ""))

        pair = FilePair(
            before_file=before_gsheet,
            after_file=after_gsheet,
            before_h5=before_h5_path,
            after_h5=after_h5_path,
            chip=chip,
            genotype=genotype,
            pair_id=pair_id,
            before_time=before_time,
            after_time=after_time,
        )
        pairs.append(pair)

        logger.info(f"Found pair {pair_id} (Chip {chip}): {before_gsheet} -> {after_gsheet}")

    logger.info(f"Total valid pairs: {len(pairs)}")
    return pairs


# =============================================================================
# H5 Data Loading
# =============================================================================

def compute_step_light_mean_response(
    unit_group: h5py.Group,
    section_name: str = STEP_SECTION_NAME,
    bin_size_ms: float = STEP_BIN_SIZE_MS,
    sample_rate: int = STEP_SAMPLE_RATE,
) -> Tuple[np.ndarray, float, Optional[np.ndarray]]:
    """
    Compute mean response to step light from trial spike times.

    Args:
        unit_group: H5 group for the unit
        section_name: Name of the step light section
        bin_size_ms: Bin size for PSTH in milliseconds
        sample_rate: Sample rate in Hz

    Returns:
        Tuple of (mean_response, quality_index, trial_responses)
    """
    default_response = np.zeros(100)

    if "spike_times_sectioned" not in unit_group:
        return default_response, 0.0, None

    sectioned = unit_group["spike_times_sectioned"]

    if section_name not in sectioned:
        return default_response, 0.0, None

    section = sectioned[section_name]

    if "trials_start_end" not in section or "trials_spike_times" not in section:
        return default_response, 0.0, None

    trials_start_end = section["trials_start_end"][:]
    n_trials = len(trials_start_end)

    if n_trials == 0:
        return default_response, 0.0, None

    trial_durations = trials_start_end[:, 1] - trials_start_end[:, 0]
    max_duration = int(np.max(trial_durations))

    bin_size_samples = int(bin_size_ms * sample_rate / 1000)
    n_bins = max_duration // bin_size_samples + 1

    if n_bins <= 0:
        return default_response, 0.0, None

    trials_group = section["trials_spike_times"]
    trial_responses = []

    for trial_idx in range(n_trials):
        trial_key = str(trial_idx)
        if trial_key not in trials_group:
            continue

        ds = trials_group[trial_key]
        if ds.shape == ():
            # Scalar dataset (single spike stored as scalar int64)
            spike_times = np.array([ds[()]])
        else:
            spike_times = ds[:]
        trial_start = trials_start_end[trial_idx, 0]
        trial_end = trials_start_end[trial_idx, 1]

        valid_spikes = spike_times[(spike_times >= trial_start) & (spike_times < trial_end)]
        relative_times = valid_spikes - trial_start

        bins = np.arange(0, max_duration + bin_size_samples, bin_size_samples)
        hist, _ = np.histogram(relative_times, bins=bins)
        firing_rate = hist * (1000 / bin_size_ms)

        trial_responses.append(firing_rate)

    if not trial_responses:
        return default_response, 0.0, None

    max_len = max(len(r) for r in trial_responses)
    padded_responses = np.zeros((len(trial_responses), max_len))
    for i, r in enumerate(trial_responses):
        padded_responses[i, : len(r)] = r

    mean_response = padded_responses.mean(axis=0)

    if padded_responses.shape[0] > 1:
        var_of_mean = np.var(mean_response)
        mean_of_var = np.mean(np.var(padded_responses, axis=1))
        if mean_of_var > 0:
            quality_index = var_of_mean / mean_of_var
        else:
            quality_index = 0.1 if var_of_mean > 0 else 0.0
    else:
        quality_index = 0.1 if np.var(mean_response) > 0 else 0.0

    return mean_response, quality_index, padded_responses


def get_quality_index(array: np.ndarray) -> float:
    """Calculate quality index for a unit's response array."""
    if array.ndim != 2 or array.shape[0] < 2:
        return np.nan

    mean_across_trials = array.mean(axis=0)
    var_across_timepoints = array.var(axis=1)

    if np.isnan(mean_across_trials).any() or np.isnan(var_across_timepoints).any():
        return np.nan

    mean_var = np.mean(var_across_timepoints)

    if mean_var == 0:
        return np.nan

    quality_index = np.var(mean_across_trials) / mean_var
    return quality_index


def cell_type_identifier(
    trace_array: np.ndarray,
    quality_threshold: float = 0.1,
    response_range: List[int] = [2, 4],
    baseline_range: List[int] = [0, 2],
    response_std_threshold: float = 0.1,
) -> bool:
    """Identify if a cell responds to stimulus based on trace array."""
    if trace_array is None or trace_array.ndim != 2 or trace_array.shape[0] < 1:
        return False

    n_bins = trace_array.shape[1]

    resp_start = max(0, response_range[0])
    resp_end = min(n_bins, response_range[1])
    base_start = max(0, baseline_range[0])
    base_end = min(n_bins, baseline_range[1]) if baseline_range[1] else n_bins

    if resp_end <= resp_start or base_end <= base_start:
        return False

    if quality_threshold is not None:
        qi = get_quality_index(trace_array)
        if np.isnan(qi) or qi < quality_threshold:
            return False

    if response_std_threshold is not None:
        response_mean = np.mean(trace_array[:, resp_start:resp_end])
        baseline_mean = np.mean(trace_array[:, base_start:base_end])
        baseline_std = np.std(trace_array[:, base_start:base_end])

        if baseline_std == 0:
            if response_mean <= baseline_mean:
                return False
        else:
            if response_mean < baseline_mean + response_std_threshold * baseline_std:
                return False

    return True


def label_cell_type(
    step_response_trials: Optional[np.ndarray],
    on_params: Dict = None,
    off_params: Dict = None,
) -> str:
    """
    Label cell type based on step response.

    Returns:
        Cell type: "ON", "OFF", "ON_OFF", or "unknown"
    """
    if step_response_trials is None or len(step_response_trials) == 0:
        return "unknown"

    if on_params is None:
        on_params = ON_CELL_PARAMS
    if off_params is None:
        off_params = OFF_CELL_PARAMS

    is_on = cell_type_identifier(
        step_response_trials,
        quality_threshold=on_params.get("quality_threshold", 0.1),
        response_range=on_params.get("response_range", [2, 4]),
        baseline_range=on_params.get("baseline_range", [0, 2]),
        response_std_threshold=on_params.get("response_std_threshold", 0.1),
    )

    is_off = cell_type_identifier(
        step_response_trials,
        quality_threshold=off_params.get("quality_threshold", 0.1),
        response_range=off_params.get("response_range", [100, 110]),
        baseline_range=off_params.get("baseline_range", [95, 100]),
        response_std_threshold=off_params.get("response_std_threshold", 0.1),
    )

    if is_on and is_off:
        return "ON_OFF"
    elif is_on and not is_off:
        return "ON"
    elif not is_on and is_off:
        return "OFF"
    else:
        return "unknown"


def load_unit_data_from_h5(
    h5_path: Path,
    step_section_name: str = STEP_SECTION_NAME,
    label_cell_types: bool = True,
) -> Dict[str, UnitData]:
    """
    Load unit data from an H5 file.

    Args:
        h5_path: Path to H5 file
        step_section_name: Name of step light section for response signature
        label_cell_types: If True, compute cell type labels

    Returns:
        Dictionary mapping unit_id to UnitData
    """
    logger = logging.getLogger(__name__)
    units = {}

    try:
        with h5py.File(h5_path, "r") as f:
            if "units" not in f:
                logger.warning(f"No 'units' group in {h5_path}")
                return units

            units_group = f["units"]
            step_found_count = 0
            cell_type_counts = {"ON": 0, "OFF": 0, "ON_OFF": 0, "unknown": 0}

            for unit_id in units_group.keys():
                unit_group = units_group[unit_id]

                row = int(unit_group.attrs.get("row", 0))
                col = int(unit_group.attrs.get("col", 0))

                waveform = np.zeros(50)
                if "waveform" in unit_group:
                    waveform = unit_group["waveform"][:]
                elif "mean_waveform" in unit_group:
                    waveform = unit_group["mean_waveform"][:]

                response_signature, quality_index, trial_responses = (
                    compute_step_light_mean_response(
                        unit_group,
                        section_name=step_section_name,
                    )
                )

                cell_type = "unknown"
                step_response_trials = None

                if len(response_signature) > 0 and np.any(response_signature != 0):
                    step_found_count += 1
                    step_response_trials = trial_responses

                    if label_cell_types and trial_responses is not None:
                        cell_type = label_cell_type(trial_responses)
                        cell_type_counts[cell_type] += 1
                else:
                    if "firing_rate_10hz" in unit_group:
                        firing_rate = unit_group["firing_rate_10hz"][:]
                        response_signature = firing_rate
                        if len(firing_rate) > 0 and np.std(firing_rate) > 0:
                            quality_index = np.var(firing_rate) / (
                                np.mean(firing_rate) + 1e-6
                            )
                            quality_index = min(quality_index, 10.0) / 10.0
                        else:
                            quality_index = 0.1
                    cell_type_counts["unknown"] += 1

                spike_times = None
                if "spike_times" in unit_group:
                    spike_times = unit_group["spike_times"][:]

                units[unit_id] = UnitData(
                    unit_id=unit_id,
                    row=row,
                    col=col,
                    waveform=waveform,
                    response_signature=response_signature,
                    quality_index=quality_index,
                    spike_times=spike_times,
                    cell_type=cell_type,
                    step_response_trials=step_response_trials,
                )

            logger.info(
                f"Loaded {len(units)} units from {h5_path.name} "
                f"({step_found_count} with step response)"
            )
            if label_cell_types:
                logger.info(
                    f"  Cell types: ON={cell_type_counts['ON']}, "
                    f"OFF={cell_type_counts['OFF']}, "
                    f"ON_OFF={cell_type_counts['ON_OFF']}, "
                    f"unknown={cell_type_counts['unknown']}"
                )

    except Exception as e:
        logger.error(f"Error loading {h5_path}: {e}")

    return units


# =============================================================================
# Quality Filtering
# =============================================================================

def filter_high_quality_units(
    units: Dict[str, UnitData],
    quality_threshold: float = DEFAULT_QUALITY_THRESHOLD,
) -> List[str]:
    """Filter units by quality index."""
    high_quality = []
    for unit_id, data in units.items():
        if not np.isnan(data.quality_index) and data.quality_index >= quality_threshold:
            high_quality.append(unit_id)
    return sorted(high_quality)


# =============================================================================
# Unit Alignment
# =============================================================================

def get_unit_pair_list(
    ref_units: Dict[str, UnitData],
    align_units: Dict[str, UnitData],
    ref_keys: List[str],
    align_keys: List[str],
    waveform_weight: float = DEFAULT_WAVEFORM_WEIGHT,
    distance_threshold: int = 0,
    verbose: bool = False,
) -> List[Tuple[str, str]]:
    """
    Find matching unit pairs between reference and alignment datasets.

    Args:
        ref_units: Reference dataset units
        align_units: Alignment dataset units
        ref_keys: List of reference unit IDs to match
        align_keys: List of alignment unit IDs to consider
        waveform_weight: Weight for waveform similarity vs response
        distance_threshold: Maximum distance (in pixels) for coordinate matching
        verbose: Print matching details

    Returns:
        List of (ref_unit_id, align_unit_id) pairs
    """
    logger = logging.getLogger(__name__)
    final_pairs = []

    for ref_key in ref_keys:
        ref_data = ref_units[ref_key]
        ref_coord = np.array([ref_data.row, ref_data.col])

        candidates = []
        response_diffs = []
        waveform_diffs = []
        sum_diffs = []

        for align_key in align_keys:
            align_data = align_units[align_key]
            align_coord = np.array([align_data.row, align_data.col])

            distance = np.linalg.norm(ref_coord - align_coord)
            if distance <= np.sqrt(distance_threshold):
                candidates.append(align_key)

                ref_resp = ref_data.response_signature
                align_resp = align_data.response_signature
                min_len = min(len(ref_resp), len(align_resp))
                if min_len > 0:
                    response_diff = np.linalg.norm(
                        ref_resp[:min_len] - align_resp[:min_len]
                    )
                else:
                    response_diff = np.inf
                response_diffs.append(response_diff)

                ref_wave = ref_data.waveform
                align_wave = align_data.waveform
                min_len = min(len(ref_wave), len(align_wave))
                if min_len > 0:
                    waveform_diff = np.linalg.norm(
                        ref_wave[:min_len] - align_wave[:min_len]
                    )
                else:
                    waveform_diff = np.inf
                waveform_diffs.append(waveform_diff)

                sum_diff = response_diff + waveform_diff * waveform_weight
                sum_diffs.append(sum_diff)

        if len(candidates) == 1:
            final_pairs.append((ref_key, candidates[0]))
            if verbose:
                logger.debug(f"Matched: {ref_key} -> {candidates[0]}")
        elif len(candidates) > 1:
            if np.argmin(response_diffs) == np.argmin(waveform_diffs):
                best_idx = np.argmin(response_diffs)
            else:
                best_idx = np.argmin(sum_diffs)
            final_pairs.append((ref_key, candidates[best_idx]))
            if verbose:
                logger.debug(f"Matched (multi): {ref_key} -> {candidates[best_idx]}")

    return final_pairs


def generate_alignment_links(
    ref_units: Dict[str, UnitData],
    align_units: Dict[str, UnitData],
    quality_threshold: float = DEFAULT_QUALITY_THRESHOLD,
    waveform_weight: float = DEFAULT_WAVEFORM_WEIGHT,
    iteration_distances: List[int] = None,
) -> Tuple[List[Tuple[str, str]], List[str], List[str]]:
    """
    Generate alignment links between two datasets using iterative matching.

    Returns:
        Tuple of (pairs, ref_high_quality, align_high_quality)
    """
    logger = logging.getLogger(__name__)

    if iteration_distances is None:
        iteration_distances = DEFAULT_ITERATION_DISTANCES

    ref_hq = filter_high_quality_units(ref_units, quality_threshold)
    align_hq = filter_high_quality_units(align_units, quality_threshold)

    logger.info(f"High-quality units: ref={len(ref_hq)}, align={len(align_hq)}")

    final_pairs = []
    remaining_ref = ref_hq.copy()
    remaining_align = align_hq.copy()

    for i, distance in enumerate(iteration_distances):
        logger.info(f"Iteration {i + 1}: distance_threshold={distance}")

        pairs = get_unit_pair_list(
            ref_units,
            align_units,
            remaining_ref,
            remaining_align,
            waveform_weight=waveform_weight,
            distance_threshold=distance,
        )

        final_pairs.extend(pairs)

        matched_ref = {p[0] for p in pairs}
        matched_align = {p[1] for p in pairs}

        remaining_ref = [k for k in remaining_ref if k not in matched_ref]
        remaining_align = [k for k in remaining_align if k not in matched_align]

        logger.info(
            f"  Matched: {len(pairs)}, remaining: "
            f"ref={len(remaining_ref)}, align={len(remaining_align)}"
        )

    logger.info(
        f"Total matched pairs: {len(final_pairs)} / {len(ref_hq)} ref units "
        f"({100 * len(final_pairs) / max(1, len(ref_hq)):.1f}%)"
    )

    return final_pairs, ref_hq, align_hq


# =============================================================================
# Merged Output
# =============================================================================

def save_aligned_pair(
    pair: FilePair,
    unit_pairs: List[Tuple[str, str]],
    ref_units: Dict[str, UnitData],
    align_units: Dict[str, UnitData],
    ref_hq: List[str],
    align_hq: List[str],
    output_dir: Path = ALIGNED_OUTPUT_DIR,
) -> Path:
    """
    Save aligned pair data to a merged H5 file.

    Returns:
        Path to saved file
    """
    logger = logging.getLogger(__name__)

    output_dir.mkdir(parents=True, exist_ok=True)

    before_stem = pair.before_h5.stem
    after_stem = pair.after_h5.stem
    output_name = f"{before_stem}_to_{after_stem}_aligned.h5"
    output_path = output_dir / output_name

    logger.info(f"Saving aligned data to {output_path}")

    with h5py.File(output_path, "w") as f:
        f.attrs["created_at"] = datetime.now().isoformat()
        f.attrs["before_file"] = pair.before_file
        f.attrs["after_file"] = pair.after_file
        f.attrs["before_h5"] = str(pair.before_h5)
        f.attrs["after_h5"] = str(pair.after_h5)
        f.attrs["chip"] = pair.chip
        f.attrs["genotype"] = pair.genotype
        f.attrs["pair_id"] = pair.pair_id
        f.attrs["before_time"] = pair.before_time.isoformat()
        f.attrs["after_time"] = pair.after_time.isoformat()
        f.attrs["num_pairs"] = len(unit_pairs)
        f.attrs["num_ref_hq"] = len(ref_hq)
        f.attrs["num_align_hq"] = len(align_hq)

        connections = f.create_group("connections")
        if unit_pairs:
            ref_ids = np.array([p[0] for p in unit_pairs], dtype="S")
            align_ids = np.array([p[1] for p in unit_pairs], dtype="S")
            connections.create_dataset("before_units", data=ref_ids)
            connections.create_dataset("after_units", data=align_ids)

        connections.create_dataset(
            "before_hq_units", data=np.array(ref_hq, dtype="S")
        )
        connections.create_dataset(
            "after_hq_units", data=np.array(align_hq, dtype="S")
        )

        paired_units = f.create_group("paired_units")
        cell_type_counts = {"ON": 0, "OFF": 0, "ON_OFF": 0, "unknown": 0}

        for i, (ref_id, align_id) in enumerate(unit_pairs):
            pair_group = paired_units.create_group(f"pair_{i:04d}")
            pair_group.attrs["before_unit"] = ref_id
            pair_group.attrs["after_unit"] = align_id

            if ref_id in ref_units:
                ref_data = ref_units[ref_id]
                before_grp = pair_group.create_group("before")
                before_grp.attrs["unit_id"] = ref_id
                before_grp.attrs["row"] = ref_data.row
                before_grp.attrs["col"] = ref_data.col
                before_grp.attrs["quality_index"] = ref_data.quality_index
                before_grp.attrs["cell_type"] = ref_data.cell_type
                before_grp.create_dataset("waveform", data=ref_data.waveform)
                before_grp.create_dataset(
                    "response_signature", data=ref_data.response_signature
                )

                if ref_data.step_response_trials is not None:
                    before_grp.create_dataset(
                        "step_response_trials", data=ref_data.step_response_trials
                    )

                cell_type_counts[ref_data.cell_type] += 1
                pair_group.attrs["cell_type"] = ref_data.cell_type

            if align_id in align_units:
                align_data = align_units[align_id]
                after_grp = pair_group.create_group("after")
                after_grp.attrs["unit_id"] = align_id
                after_grp.attrs["row"] = align_data.row
                after_grp.attrs["col"] = align_data.col
                after_grp.attrs["quality_index"] = align_data.quality_index
                after_grp.attrs["cell_type"] = align_data.cell_type
                after_grp.create_dataset("waveform", data=align_data.waveform)
                after_grp.create_dataset(
                    "response_signature", data=align_data.response_signature
                )

                if align_data.step_response_trials is not None:
                    after_grp.create_dataset(
                        "step_response_trials", data=align_data.step_response_trials
                    )

        f.attrs["cell_type_on"] = cell_type_counts["ON"]
        f.attrs["cell_type_off"] = cell_type_counts["OFF"]
        f.attrs["cell_type_on_off"] = cell_type_counts["ON_OFF"]
        f.attrs["cell_type_unknown"] = cell_type_counts["unknown"]

    logger.info(f"Saved {len(unit_pairs)} aligned pairs to {output_path.name}")
    return output_path


# =============================================================================
# Main Pipeline
# =============================================================================

def process_alignment_pair(
    pair: FilePair,
    quality_threshold: float = DEFAULT_QUALITY_THRESHOLD,
    waveform_weight: float = DEFAULT_WAVEFORM_WEIGHT,
    iteration_distances: List[int] = None,
    output_dir: Path = ALIGNED_OUTPUT_DIR,
    overwrite: bool = False,
) -> Optional[Path]:
    """Process a single alignment pair."""
    logger = logging.getLogger(__name__)

    # Check if output already exists
    before_stem = pair.before_h5.stem
    after_stem = pair.after_h5.stem
    output_name = f"{before_stem}_to_{after_stem}_aligned.h5"
    output_path = output_dir / output_name

    if output_path.exists() and not overwrite:
        logger.info(f"Skipped pair {pair.pair_id} - output already exists: {output_name}")
        return output_path

    logger.info(f"Processing pair {pair.pair_id}: {pair.before_file} -> {pair.after_file}")

    ref_units = load_unit_data_from_h5(pair.before_h5)
    align_units = load_unit_data_from_h5(pair.after_h5)

    if not ref_units:
        logger.error(f"No units loaded from {pair.before_h5}")
        return None

    if not align_units:
        logger.error(f"No units loaded from {pair.after_h5}")
        return None

    unit_pairs, ref_hq, align_hq = generate_alignment_links(
        ref_units,
        align_units,
        quality_threshold=quality_threshold,
        waveform_weight=waveform_weight,
        iteration_distances=iteration_distances,
    )

    output_path = save_aligned_pair(
        pair,
        unit_pairs,
        ref_units,
        align_units,
        ref_hq,
        align_hq,
        output_dir=output_dir,
    )

    return output_path


def run_alignment_pipeline(
    index_csv: Path = FILE_INDEX_CSV,
    h5_folder: Path = OUTPUT_DIR,
    output_dir: Path = ALIGNED_OUTPUT_DIR,
    quality_threshold: float = DEFAULT_QUALITY_THRESHOLD,
    waveform_weight: float = DEFAULT_WAVEFORM_WEIGHT,
    iteration_distances: List[int] = None,
    overwrite: bool = False,
) -> List[Path]:
    """
    Run the full alignment pipeline.

    Args:
        index_csv: Path to file_index.csv
        h5_folder: Folder containing H5 files
        output_dir: Output folder for aligned files
        quality_threshold: Quality index threshold
        waveform_weight: Waveform weight
        iteration_distances: Distance thresholds
        overwrite: Whether to overwrite existing aligned files

    Returns:
        List of output file paths
    """
    logger = logging.getLogger(__name__)

    logger.info("=" * 60)
    logger.info("Blocker Alignment Pipeline")
    logger.info("=" * 60)

    # Find pairs from CSV index
    pairs = find_alignment_pairs_from_index(index_csv, h5_folder)

    if not pairs:
        logger.warning("No alignment pairs found")
        return []

    output_files = []

    for i, pair in enumerate(pairs):
        logger.info(f"\n[{i + 1}/{len(pairs)}] Processing alignment pair")

        try:
            output_path = process_alignment_pair(
                pair,
                quality_threshold=quality_threshold,
                waveform_weight=waveform_weight,
                iteration_distances=iteration_distances,
                output_dir=output_dir,
                overwrite=overwrite,
            )

            if output_path:
                output_files.append(output_path)

        except Exception as e:
            logger.error(f"Error processing pair: {e}")
            continue

    logger.info("=" * 60)
    logger.info(f"Alignment complete: {len(output_files)}/{len(pairs)} pairs processed")
    logger.info("=" * 60)

    return output_files


# =============================================================================
# Main Entry Point
# =============================================================================

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Align units across before/after recording pairs for blocker analysis"
    )
    parser.add_argument(
        "--experiment",
        type=str,
        default=None,
        help="Experiment profile key (e.g. _ptx_str, _ptx, _str). "
             "Already resolved at import time; accepted here so argparse "
             "does not reject the flag.",
    )
    parser.add_argument(
        "--index-csv",
        type=Path,
        default=FILE_INDEX_CSV,
        help=f"File index CSV (default: {FILE_INDEX_CSV})",
    )
    parser.add_argument(
        "--h5-folder",
        type=Path,
        default=OUTPUT_DIR,
        help=f"Folder containing H5 files (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ALIGNED_OUTPUT_DIR,
        help=f"Output directory (default: {ALIGNED_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--quality-threshold",
        type=float,
        default=DEFAULT_QUALITY_THRESHOLD,
        help=f"Quality index threshold (default: {DEFAULT_QUALITY_THRESHOLD})",
    )
    parser.add_argument(
        "--waveform-weight",
        type=float,
        default=DEFAULT_WAVEFORM_WEIGHT,
        help=f"Waveform weight (default: {DEFAULT_WAVEFORM_WEIGHT})",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing aligned files (default: skip existing)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    args = parser.parse_args()

    setup_logging(level=logging.DEBUG if args.debug else logging.INFO)

    print("=" * 70)
    print("Blocker Alignment Pipeline")
    print("=" * 70)
    print(f"Experiment:   {ACTIVE_EXPERIMENT}")
    print(f"Index CSV:    {args.index_csv}")
    print(f"H5 Folder:    {args.h5_folder}")
    print(f"Output:       {args.output}")
    print(f"Quality:      {args.quality_threshold}")
    print(f"Waveform Wt:  {args.waveform_weight}")
    print(f"Overwrite:    {args.overwrite}")
    print(f"Started:      {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)

    output_files = run_alignment_pipeline(
        index_csv=args.index_csv,
        h5_folder=args.h5_folder,
        output_dir=args.output,
        quality_threshold=args.quality_threshold,
        waveform_weight=args.waveform_weight,
        overwrite=args.overwrite,
    )

    print()
    print("=" * 70)
    print(f"Complete: {len(output_files)} aligned files created")
    for f in output_files:
        print(f"  - {f.name}")
    print("=" * 70)


if __name__ == "__main__":
    main()
