#!/usr/bin/env python
"""
Batch Processing: Blocker Alignment Analysis Pipeline

Processes CMCR/CMTR recordings from the file index CSV generated by
discover_files.py. Uses dynamic playlist selection based on the Condition
column (extracting the part before the first comma).

Usage:
    python batch_pipeline.py
    python batch_pipeline.py --start 0 --end 10
    python batch_pipeline.py --overwrite
    python batch_pipeline.py --skip_existing

Steps executed (when playlist available):
- Step 1: Load recording with eimage_sta
- Step 2: Add section time from playlist (dynamic)
- Step 3: Section spike times
- Step 3b: Add section time from analog signal
- Step 3c: Section spike times for analog stimuli
- Step 4: Compute STA
- Step 5: Add CMTR/CMCR metadata
- Step 6: Extract soma geometry
- Step 7: Extract RF geometry
- Step 8: Add Google Sheet metadata
- Step 9: Add axon labels (blocker-specific)
- Step 10: Compute AP tracking
- Step 11: Section by direction (DSGC)

Steps executed (basic load only):
- Step 1: Load recording with eimage_sta
- Step 5: Add CMTR/CMCR metadata
- Step 8: Add Google Sheet metadata
"""

import argparse
import logging
import re
import sys
import time
import traceback
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import pandas as pd

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root / "src"))
sys.path.insert(0, str(project_root))

from hdmea.pipeline import create_session

# Import step wrappers from unified pipeline
from Projects.unified_pipeline.steps import (
    load_recording_step,
    add_section_time_step,
    add_section_time_analog_step,
    section_spike_times_step,
    section_spike_times_analog_step,
    compute_sta_step,
    add_metadata_step,
    extract_soma_geometry_step,
    extract_rf_geometry_step,
    add_gsheet_step,
    compute_ap_tracking_step,
    section_by_direction_step,
)

# Import config classes from unified pipeline
from Projects.unified_pipeline.config import (
    setup_logging,
    LoadRecordingConfig,
    SectionTimeConfig,
    SectionTimeAnalogConfig,
    GeometryConfig,
    APTrackingConfig,
    DSGCConfig,
    green_success,
    red_warning,
)

# Import local config (handle both module and direct execution)
try:
    from .specific_config import (
        ACTIVE_EXPERIMENT,
        OUTPUT_DIR,
        LABEL_ROOT,
        GSHEET_CSV_PATH,
        PLAYLIST_CSV_PATH,
        FILE_INDEX_CSV,
        get_dataset_id_from_cmcr,
        get_cmcr_cmtr_paths,
        parse_condition_for_playlist,
    )
except ImportError:
    from specific_config import (
        ACTIVE_EXPERIMENT,
        OUTPUT_DIR,
        LABEL_ROOT,
        GSHEET_CSV_PATH,
        PLAYLIST_CSV_PATH,
        FILE_INDEX_CSV,
        get_dataset_id_from_cmcr,
        get_cmcr_cmtr_paths,
        parse_condition_for_playlist,
    )

logger = logging.getLogger(__name__)

# =============================================================================
# Axon Label Configuration
# =============================================================================

# Cell type labels (subfolder names under each dataset_id folder)
CELL_TYPES = ["RGC", "AC", "Other", "Unknown"]

# Step name, auto_label group, and feature (same keys as cell_type.py)
STEP_NAME_AXON_LABEL = "add_cell_type_labels"
AUTO_LABEL_GROUP = "auto_label"
FEATURE_NAME = "axon_type"


# =============================================================================
# Playlist Resolution
# =============================================================================

def load_available_playlists(playlist_csv_path: Path = PLAYLIST_CSV_PATH) -> Set[str]:
    """
    Load available playlist names from CSV.

    Args:
        playlist_csv_path: Path to playlist.csv

    Returns:
        Set of available playlist names
    """
    logger = logging.getLogger(__name__)

    if not playlist_csv_path.exists():
        logger.warning(f"Playlist CSV not found: {playlist_csv_path}")
        return set()

    try:
        df = pd.read_csv(playlist_csv_path)
        playlists = set(df["playlist_name"].dropna().tolist())
        logger.debug(f"Loaded {len(playlists)} playlists from {playlist_csv_path}")
        return playlists
    except Exception as e:
        logger.error(f"Failed to load playlist CSV: {e}")
        return set()


def load_gsheet_dataframe(gsheet_csv_path: Path = GSHEET_CSV_PATH) -> Optional[pd.DataFrame]:
    """
    Load gsheet data from CSV cache.

    Args:
        gsheet_csv_path: Path to gsheet_table.csv

    Returns:
        DataFrame with gsheet data, or None if load fails
    """
    logger = logging.getLogger(__name__)

    if not gsheet_csv_path.exists():
        logger.warning(f"Gsheet CSV not found: {gsheet_csv_path}")
        return None

    try:
        df = pd.read_csv(gsheet_csv_path)
        logger.debug(f"Loaded {len(df)} rows from gsheet CSV")
        return df
    except Exception as e:
        logger.error(f"Failed to load gsheet CSV: {e}")
        return None


def resolve_playlist(
    condition: Optional[str],
    available_playlists: Set[str],
) -> Optional[str]:
    """
    Resolve condition to playlist name.

    First extracts the part before the first comma from the condition,
    then strips trailing "()" and checks against available playlists.

    Example:
        "play_optimization_set6_a_ipRGC_manual(), gaba, glycine"
        -> extract: "play_optimization_set6_a_ipRGC_manual()"
        -> strip (): "play_optimization_set6_a_ipRGC_manual"
        -> check playlists

    Args:
        condition: Condition value from gsheet
        available_playlists: Set of available playlist names

    Returns:
        Playlist name if found, None otherwise
    """
    if not condition:
        return None

    # Extract part before first comma
    playlist_condition = parse_condition_for_playlist(condition)

    # Strip trailing "()" if present
    playlist_name = playlist_condition.rstrip("()")

    # Check if it's in the available playlists
    if playlist_name in available_playlists:
        return playlist_name

    return None


# =============================================================================
# Axon Label Parsing
# =============================================================================

def find_dataset_label_folder(
    label_root: Path,
    dataset_id: str,
) -> Optional[Path]:
    """
    Search all condition subfolders for a dataset_id match.

    The label_root has condition subfolders, each containing
    dataset_id subfolders. We need to find which condition folder
    contains our dataset_id.

    Args:
        label_root: Root of the label folder hierarchy
        dataset_id: Dataset identifier (e.g., "2025.09.04-10.11.09-Rec")

    Returns:
        Path to the dataset folder, or None if not found
    """
    if not label_root.exists():
        logger.warning(f"Label root not found: {label_root}")
        return None

    # Search each condition subfolder
    for condition_folder in sorted(label_root.iterdir()):
        if not condition_folder.is_dir():
            continue

        dataset_folder = condition_folder / dataset_id
        if dataset_folder.exists() and dataset_folder.is_dir():
            logger.debug(
                f"  Found label folder: {condition_folder.name}/{dataset_id}"
            )
            return dataset_folder

    # Not found with exact name -- try with dot/hyphen normalization
    # H5 dataset_id uses hyphens: 2025.09.04-10.11.09-Rec
    # Some folders might use dots: 2025.09.04.10.11.09.Rec
    alt_id = dataset_id.replace("-", ".")
    for condition_folder in sorted(label_root.iterdir()):
        if not condition_folder.is_dir():
            continue

        alt_folder = condition_folder / alt_id
        if alt_folder.exists() and alt_folder.is_dir():
            logger.debug(
                f"  Found label folder (alt): {condition_folder.name}/{alt_id}"
            )
            return alt_folder

    return None


def parse_axon_labels(
    dataset_folder: Path,
    cell_types: List[str] = None,
) -> Dict[int, str]:
    """
    Parse manual axon labels from folder structure.

    Reads the cell type subfolders (RGC, AC, Other, Unknown) and extracts
    unit numbers from PNG filenames.

    Args:
        dataset_folder: Path to the dataset folder containing cell type subfolders
        cell_types: List of cell type subfolder names to search

    Returns:
        Dict mapping unit number (int) to cell type label (str, lowercase)
    """
    if cell_types is None:
        cell_types = CELL_TYPES

    labels = {}

    for cell_type in cell_types:
        cell_type_folder = dataset_folder / cell_type

        if not cell_type_folder.exists():
            continue

        # Find all PNG files (including nested)
        png_files = list(cell_type_folder.rglob("*.png"))

        for png_file in png_files:
            # Extract unit number from filename like
            # "2025.09.04-10.11.09-Rec_unit10.png"
            match = re.search(r"_unit(\d+)\.png$", png_file.name, re.IGNORECASE)
            if match:
                unit_num = int(match.group(1))
                labels[unit_num] = cell_type.lower()

    return labels


def add_axon_label_step(
    *,
    label_root: Path = LABEL_ROOT,
    session: "PipelineSession",
) -> "PipelineSession":
    """
    Add manual axon_type labels to units from the blocker label folder.

    Searches all condition subfolders in label_root for the dataset_id,
    then reads cell type labels from the RGC/AC/Other/Unknown subfolders.

    Args:
        label_root: Root of the blocker label folder hierarchy
        session: Pipeline session (required)

    Returns:
        Updated session with axon_type labels
    """
    logger.info(f"Adding axon labels for {session.dataset_id}...")

    # Find the label folder for this dataset
    dataset_folder = find_dataset_label_folder(label_root, session.dataset_id)

    if dataset_folder is None:
        logger.warning(f"  No label folder found for {session.dataset_id}")
        session.warnings.append(f"{STEP_NAME_AXON_LABEL}: No label folder found")
        # Still mark as complete so downstream steps can run
        session.mark_step_complete(STEP_NAME_AXON_LABEL)
        return session

    # Parse labels from folder structure
    labels = parse_axon_labels(dataset_folder)

    if not labels:
        logger.warning(f"  No labels parsed from {dataset_folder}")
        session.warnings.append(f"{STEP_NAME_AXON_LABEL}: No labels parsed")

    # Apply labels to units
    labeled_count = 0
    no_label_count = 0

    for unit_id in session.units.keys():
        # Extract unit number from unit_id (e.g., "unit_001" -> 1)
        match = re.search(r"unit_(\d+)", unit_id)
        if match:
            unit_num = int(match.group(1))

            if unit_num in labels:
                cell_type = labels[unit_num]
                labeled_count += 1
            else:
                cell_type = "no_label"
                no_label_count += 1
        else:
            cell_type = "no_label"
            no_label_count += 1

        # Add auto_label group with axon_type
        if AUTO_LABEL_GROUP not in session.units[unit_id]:
            session.units[unit_id][AUTO_LABEL_GROUP] = {}

        session.units[unit_id][AUTO_LABEL_GROUP][FEATURE_NAME] = cell_type

    logger.info(
        f"  Axon labels: {labeled_count} labeled, {no_label_count} no_label "
        f"(from {dataset_folder.parent.name}/{dataset_folder.name})"
    )

    session.mark_step_complete(STEP_NAME_AXON_LABEL)
    return session


# =============================================================================
# Single Recording Processing
# =============================================================================

def process_single_recording(
    cmcr_path: Path,
    cmtr_path: Path,
    output_dir: Path,
    playlist_name: Optional[str] = None,
    gsheet_df: Optional[pd.DataFrame] = None,
    load_config: Optional[LoadRecordingConfig] = None,
    section_config: Optional[SectionTimeConfig] = None,
    section_analog_config: Optional[SectionTimeAnalogConfig] = None,
    geometry_config: Optional[GeometryConfig] = None,
    ap_config: Optional[APTrackingConfig] = None,
    dsgc_config: Optional[DSGCConfig] = None,
    label_root: Path = LABEL_ROOT,
    overwrite: bool = False,
) -> Tuple[bool, Optional[str]]:
    """
    Process a single recording.

    If playlist_name is provided, runs full 11-step pipeline.
    Otherwise, runs basic loading only (steps 1, 5, 8).

    Args:
        cmcr_path: Path to CMCR file
        cmtr_path: Path to CMTR file
        output_dir: Output directory
        playlist_name: Playlist name for section time (None for basic load)
        gsheet_df: Pre-loaded gsheet DataFrame for add_gsheet_step
        load_config: Configuration for loading
        section_config: Configuration for sectioning
        section_analog_config: Configuration for analog section time
        geometry_config: Configuration for geometry extraction
        ap_config: Configuration for AP tracking
        dsgc_config: Configuration for DSGC
        label_root: Root folder for blocker-specific axon labels
        overwrite: Whether to overwrite existing files

    Returns:
        Tuple of (success: bool, error_message: Optional[str])
    """
    logger = logging.getLogger(__name__)

    # Use default configs if not provided
    if load_config is None:
        load_config = LoadRecordingConfig()
    if section_config is None:
        section_config = SectionTimeConfig()
    if section_analog_config is None:
        section_analog_config = SectionTimeAnalogConfig()
    if geometry_config is None:
        geometry_config = GeometryConfig()
    if ap_config is None:
        ap_config = APTrackingConfig()
    if dsgc_config is None:
        dsgc_config = DSGCConfig()

    dataset_id = get_dataset_id_from_cmcr(cmcr_path.name)
    output_path = output_dir / f"{dataset_id}.h5"

    # Check if output already exists
    if output_path.exists() and not overwrite:
        return True, "skipped"

    # Validate input files exist
    if not cmcr_path.exists():
        return False, f"CMCR file not found: {cmcr_path}"

    if not cmtr_path.exists():
        return False, f"CMTR file not found: {cmtr_path}"

    mode = "full pipeline" if playlist_name else "basic load"
    logger.info(f"Processing {dataset_id} ({mode})...")
    if playlist_name:
        logger.info(f"  Playlist: {playlist_name}")
    logger.debug(f"  CMCR: {cmcr_path}")
    logger.debug(f"  CMTR: {cmtr_path}")

    # =========================================================================
    # Step 1: Load recording with eimage_sta (always run)
    # =========================================================================
    session = create_session(dataset_id=dataset_id)
    session = load_recording_step(
        cmcr_path=cmcr_path,
        cmtr_path=cmtr_path,
        duration_s=load_config.duration_s,
        spike_limit=load_config.spike_limit,
        window_range=load_config.window_range,
        session=session,
    )

    if playlist_name:
        # =================================================================
        # Full Pipeline: Steps 2-11
        # =================================================================

        # Step 2: Add section time from playlist (dynamic)
        session = add_section_time_step(
            playlist_name=playlist_name,
            session=session,
        )

        # Step 3: Section spike times
        session = section_spike_times_step(
            pad_margin=section_config.pad_margin,
            session=session,
        )

        # Step 3b: Add section time from analog signal
        session = add_section_time_analog_step(
            config=section_analog_config,
            session=session,
        )

        # Step 3c: Section spike times for analog stimuli
        session = section_spike_times_analog_step(
            movie_name=section_analog_config.movie_name,
            pad_margin=section_analog_config.pad_margin,
            session=session,
        )

        # Step 4: Compute STA
        session = compute_sta_step(
            cover_range=section_config.cover_range,
            session=session,
        )

        # Step 5: Add metadata
        session = add_metadata_step(session=session)

        # Step 6: Extract soma geometry
        session = extract_soma_geometry_step(
            frame_range=geometry_config.frame_range,
            threshold_fraction=geometry_config.threshold_fraction,
            session=session,
        )

        # Step 7: Extract RF geometry
        session = extract_rf_geometry_step(
            frame_range=geometry_config.frame_range,
            threshold_fraction=geometry_config.threshold_fraction,
            session=session,
        )

        # Step 8: Add gsheet metadata
        session = add_gsheet_step(
            gsheet_df=gsheet_df,
            session=session,
        )

        # Step 9: Add axon labels (blocker-specific)
        session = add_axon_label_step(label_root=label_root, session=session)

        # Step 10: Compute AP tracking
        session = compute_ap_tracking_step(
            config=ap_config,
            session=session,
        )

        # Step 11: Section by direction (DSGC)
        session = section_by_direction_step(
            config=dsgc_config,
            session=session,
        )
    else:
        # =================================================================
        # Basic Load: Steps 1, 5, 8 only
        # =================================================================

        # Step 5: Add metadata
        session = add_metadata_step(session=session)

        # Step 8: Add gsheet metadata
        session = add_gsheet_step(
            gsheet_df=gsheet_df,
            session=session,
        )

    # =========================================================================
    # Save final result
    # =========================================================================
    session.save(output_path=output_path, overwrite=overwrite)

    logger.info(f"  Saved: {output_path}")
    logger.info(f"  Units: {session.unit_count}, Steps: {len(session.completed_steps)}")

    if session.warnings:
        logger.debug(f"  Warnings: {len(session.warnings)}")

    return True, None


# =============================================================================
# Batch Processing
# =============================================================================

def load_file_index(index_csv: Path = FILE_INDEX_CSV) -> Optional[pd.DataFrame]:
    """
    Load the file index CSV generated by discover_files.py.

    Args:
        index_csv: Path to file_index.csv

    Returns:
        DataFrame with file index, or None if not found
    """
    logger = logging.getLogger(__name__)

    if not index_csv.exists():
        logger.error(
            f"File index not found: {index_csv}\n"
            f"Run discover_files.py first to generate the index."
        )
        return None

    try:
        df = pd.read_csv(index_csv)
        logger.info(f"Loaded file index: {len(df)} rows from {index_csv}")
        return df
    except Exception as e:
        logger.error(f"Failed to load file index: {e}")
        return None


def run_batch(
    index_csv: Path = FILE_INDEX_CSV,
    output_dir: Path = OUTPUT_DIR,
    label_root: Path = LABEL_ROOT,
    start_index: int = 0,
    end_index: Optional[int] = None,
    overwrite: bool = False,
    skip_existing: bool = False,
) -> Tuple[List[str], List[str], List[Tuple[str, str]]]:
    """
    Run batch processing on files from the CSV index.

    Args:
        index_csv: Path to file_index.csv
        output_dir: Output directory for HDF5 files
        label_root: Root folder for blocker-specific axon labels
        start_index: Starting index (0-based)
        end_index: Ending index (exclusive, None for all)
        overwrite: Whether to overwrite existing files
        skip_existing: Whether to skip files that already have H5 output

    Returns:
        Tuple of (successful, skipped, failed) lists
    """
    logger = logging.getLogger(__name__)

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load file index
    index_df = load_file_index(index_csv)
    if index_df is None:
        return [], [], [("file_index", "File index not found")]

    # Filter to rows where both CMCR and CMTR exist
    valid_mask = index_df["cmcr_exists"] & index_df["cmtr_exists"]
    valid_df = index_df[valid_mask].copy()
    logger.info(f"Valid recordings (both files exist): {len(valid_df)}/{len(index_df)}")

    if valid_df.empty:
        logger.warning("No valid recordings found")
        return [], [], []

    # Apply index range
    all_rows = valid_df.reset_index(drop=True)
    if end_index is not None:
        rows_to_process = all_rows.iloc[start_index:end_index]
    else:
        rows_to_process = all_rows.iloc[start_index:]

    logger.info(f"Processing {len(rows_to_process)} of {len(all_rows)} valid recordings")

    # Load playlist and gsheet data
    logger.info("Loading configuration data...")
    available_playlists = load_available_playlists()
    gsheet_df = load_gsheet_dataframe()

    if not available_playlists:
        logger.warning("No playlists loaded - all files will use basic load")

    if gsheet_df is None:
        logger.warning("Gsheet not loaded - condition lookup will fail")

    # Track results
    successful: List[str] = []
    skipped: List[str] = []
    failed: List[Tuple[str, str]] = []

    # Process each file
    start_time = time.time()

    for i, (_, row) in enumerate(rows_to_process.iterrows(), 1):
        cmcr_path = Path(row["cmcr_path"])
        cmtr_path = Path(row["cmtr_path"])
        disk_cmcr = str(row["disk_cmcr"])
        dataset_id = get_dataset_id_from_cmcr(disk_cmcr)

        logger.info(f"\n{'='*60}")
        logger.info(f"[{i}/{len(rows_to_process)}] {dataset_id}")
        logger.info(f"{'='*60}")

        try:
            # Resolve playlist from condition (using part before first comma)
            condition = str(row.get("condition", ""))
            playlist_name = None

            if condition and available_playlists:
                playlist_name = resolve_playlist(condition, available_playlists)
                if playlist_name:
                    logger.info(f"  Condition: {condition}")
                    logger.info(f"  Resolved playlist: {playlist_name}")
                else:
                    logger.info(f"  Condition: {condition} (no matching playlist)")

            # Process the recording
            success, error = process_single_recording(
                cmcr_path=cmcr_path,
                cmtr_path=cmtr_path,
                output_dir=output_dir,
                playlist_name=playlist_name,
                gsheet_df=gsheet_df,
                label_root=label_root,
                overwrite=overwrite,
            )

            if success:
                if error == "skipped":
                    logger.info(f"  Skipped - output file already exists")
                    skipped.append(dataset_id)
                else:
                    successful.append(dataset_id)
            else:
                logger.error(f"  Failed: {error}")
                failed.append((dataset_id, error or "Unknown error"))

        except Exception as e:
            logger.error(f"  Exception: {e}")
            logger.debug(traceback.format_exc())
            failed.append((dataset_id, str(e)))

    # Summary
    elapsed = time.time() - start_time

    logger.info(f"\n{'='*60}")
    logger.info("BATCH PROCESSING COMPLETE")
    logger.info(f"{'='*60}")
    logger.info(f"Total files processed: {len(rows_to_process)}")
    logger.info(f"Successful: {len(successful)}")
    logger.info(f"Skipped (already exists): {len(skipped)}")
    logger.info(f"Failed: {len(failed)}")
    logger.info(f"Time: {elapsed:.1f}s ({elapsed/60:.1f} min)")

    if failed:
        logger.info("\nFailed recordings:")
        for dataset_id, error in failed[:10]:
            logger.info(f"  - {dataset_id}: {error}")
        if len(failed) > 10:
            logger.info(f"  ... and {len(failed) - 10} more")

    return successful, skipped, failed


# =============================================================================
# Main
# =============================================================================

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Batch process blocker alignment recordings from CSV index"
    )
    parser.add_argument(
        "--experiment",
        type=str,
        default=None,
        help="Experiment profile key (e.g. _ptx_str, _ptx, _str). "
             "Already resolved at import time; accepted here so argparse "
             "does not reject the flag.",
    )
    parser.add_argument(
        "--index-csv",
        type=Path,
        default=FILE_INDEX_CSV,
        help=f"File index CSV (default: {FILE_INDEX_CSV})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_DIR,
        help=f"Output directory (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--start",
        type=int,
        default=0,
        help="Starting index (0-based, default: 0)",
    )
    parser.add_argument(
        "--end",
        type=int,
        default=None,
        help="Ending index (exclusive, default: all)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files",
    )
    parser.add_argument(
        "--label-root",
        type=Path,
        default=LABEL_ROOT,
        help=f"Axon label root folder (default: {LABEL_ROOT})",
    )
    parser.add_argument(
        "--skip_existing",
        action="store_true",
        help="Skip recordings that already have H5 output (default behavior)",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug logging",
    )

    args = parser.parse_args()

    # Setup logging
    setup_logging(level=logging.DEBUG if args.debug else logging.INFO)

    print("=" * 70)
    print("Batch Processing: Blocker Alignment Analysis Pipeline")
    print("=" * 70)
    print(f"Experiment:  {ACTIVE_EXPERIMENT}")
    print(f"Index CSV:   {args.index_csv}")
    print(f"Output:      {args.output}")
    print(f"Label root:  {args.label_root}")
    print(f"Range:       {args.start} to {args.end or 'end'}")
    print(f"Overwrite:   {args.overwrite}")
    print(f"Started:     {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)

    try:
        successful, skipped, failed = run_batch(
            index_csv=args.index_csv,
            output_dir=args.output,
            label_root=args.label_root,
            start_index=args.start,
            end_index=args.end,
            overwrite=args.overwrite,
        )

        print("\n" + "=" * 70)
        if len(failed) == 0:
            print(green_success("BATCH COMPLETE - ALL SUCCESSFUL"))
        else:
            print(red_warning(f"BATCH COMPLETE - {len(failed)} FAILED"))
        print("=" * 70)
        print(f"Successful: {len(successful)}")
        print(f"Skipped:    {len(skipped)}")
        print(f"Failed:     {len(failed)}")

    except Exception as e:
        print(red_warning(f"\nBatch processing failed: {e}"))
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
